/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Home;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bryce
 */
public class ResultPage_Form extends javax.swing.JFrame {
    
    private int uid;
    private String category;

    /**
     * Creates new form ResultPage_Form
     */
    public ResultPage_Form(int uid, String category) {
        initComponents();
        this.uid = uid;
        this.category = category;
        tableLabel.setText(category);
        tableLabel.setHorizontalAlignment(SwingConstants.CENTER);
        tableLabel.setVerticalAlignment(SwingConstants.CENTER);
        setupTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        viewTable = new javax.swing.JTable();
        tableLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        viewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Quantity", "Added By", "Date Modified"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        viewTable.getTableHeader().setReorderingAllowed(false);
        scrollPane.setViewportView(viewTable);
        if (viewTable.getColumnModel().getColumnCount() > 0) {
            viewTable.getColumnModel().getColumn(1).setPreferredWidth(1);
        }

        tableLabel.setFont(new java.awt.Font("Cantarell", 1, 20)); // NOI18N
        tableLabel.setText("Text");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
                    .addComponent(tableLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(tableLabel)
                .addGap(34, 34, 34)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setupTable() {
        DefaultTableModel m = (DefaultTableModel) viewTable.getModel();
        
        String uname = null;
        
        Connection c = Connector.getInstance();
        ResultSet rs;
        try {
            Statement statement = c.createStatement();
            String qString = "SELECT I.item, I.quantity, L2.uname, I.dateAdd "+
                             "FROM Logins as L1, Items as I, Logins as L2 "+
                             "WHERE L1.uid=I.ownedBy and I.ownedBy=? and I.category=? and L2.uid=I.addedBy "+
                             "ORDER BY I.dateAdd desc;";
            PreparedStatement query = c.prepareStatement(qString);
            query.setInt(1, uid);
            query.setString(2, category);
            
            System.out.println(query.toString());
            rs = query.executeQuery();
            while (rs.next()) {
                m.addRow(new Object[] {
                    rs.getString(1),
                    rs.getInt(2),
                    rs.getString(3),
                    rs.getDate(4)
                });
            }            
        } catch (SQLException ex) {
            Logger.getLogger(Login_Form.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JLabel tableLabel;
    private javax.swing.JTable viewTable;
    // End of variables declaration//GEN-END:variables
}
