/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Home;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author bryce
 */
public class UpdateItem extends javax.swing.JDialog {
    
    private String cat = null;
    private String item = null;
    private String quant = null;
    private int uid, itemID, quantInt;

    /**
     * Creates new form UpdateItem
     */
    public UpdateItem(java.awt.Frame parent, boolean modal, int uid, String category, int itemID) {
        super(parent, modal);
        initComponents();
        this.uid = uid;
        this.itemID = itemID;
        cat = category;
        setupFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemLabel = new javax.swing.JLabel();
        itemField = new javax.swing.JTextField();
        quantLabel = new javax.swing.JLabel();
        quantField = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        itemLabel.setText("Item:");

        itemField.setText("Item name");
        itemField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                itemFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                itemFieldFocusLost(evt);
            }
        });

        quantLabel.setText("Quantity:");

        quantField.setText("Quantity");
        quantField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                quantFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                quantFieldFocusLost(evt);
            }
        });

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(itemLabel)
                    .addComponent(quantLabel))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(quantField)
                    .addComponent(itemField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(submitButton)
                .addGap(18, 18, 18)
                .addComponent(cancelButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemLabel)
                    .addComponent(itemField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantLabel)
                    .addComponent(quantField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitButton)
                    .addComponent(cancelButton))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemFieldFocusGained
        
    }//GEN-LAST:event_itemFieldFocusGained

    private void itemFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemFieldFocusLost
        item = itemField.getText().trim();
    }//GEN-LAST:event_itemFieldFocusLost

    private void quantFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quantFieldFocusGained

    }//GEN-LAST:event_quantFieldFocusGained

    private void quantFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_quantFieldFocusLost
        quant = quantField.getText().trim();
    }//GEN-LAST:event_quantFieldFocusLost

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        if (item == null || quant == null) {
            JOptionPane.showMessageDialog(null, "Please fill all fields");
            return;
        }

        try {
            quantInt = Integer.parseInt(quant);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, quant + "is not an integer");
            return;
        }


        Connection c = Connector.getInstance();
        ResultSet rs;
        try {
            String uString = "UPDATE Items " +
                             "SET item=?, quantity=?, addedBy=?, dateAdd=? "+
                             "WHERE id=?;";
            PreparedStatement update = c.prepareStatement(uString);
            update.setString(1, item);
            update.setInt(2, quantInt);
            update.setInt(3, uid);
            update.setString(4, java.time.LocalDate.now().toString());
            update.setInt(5, itemID);
            
            System.out.println(update.toString());
            update.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(Login_Form.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(null, "Item updated");
        dispose();
    }//GEN-LAST:event_submitButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void setupFields() {
        Connection c = Connector.getInstance();
        ResultSet rs;
        
        try {           
            String qString = "SELECT item, quantity FROM Items WHERE id=?";
            PreparedStatement query = c.prepareStatement(qString);
            query.setInt(1, itemID);
            
            rs = query.executeQuery();
            while (rs.next()) {
                item = rs.getString(1);
                quantInt = rs.getInt(2);
            }
        } catch (SQLException ex) {
            Logger.getLogger(UpdateItem.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        itemField.setText(item);
        quantField.setText(Integer.toString(quantInt));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField itemField;
    private javax.swing.JLabel itemLabel;
    private javax.swing.JTextField quantField;
    private javax.swing.JLabel quantLabel;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
